<div class="row justify-content-center">
	<div class="col-6 pt-2">
		<form method="post"  class="form-inline input-group">
			<select  class="form-control input-group-select" id="ListRole" name="user_id">
				<?php foreach($clients as $client) : ?>
					<option value="<?= $client['id'] ?>" <?= $user['user_id'] == $client['id'] ? 'selected="selected"' : "" ?>><?= htmlspecialchars($client['fname'].' '.$client['lname'].' '.$client['email']) ?></option>
				<?php endforeach ?>
			</select>
			<button type="submit" class="btn btn-primary"><span class="material-symbols-outlined">check</span></button>
		</form>

		<form method="post" action="events">
		<input type="text" name="user_id" class="form-control d-none" id="InputID" value="<?= isset($user['user_id']) ? htmlspecialchars($user['user_id']) : "" ?>">
		<select  class="form-control my-1" id="ListProducts" name="product_id">
			<?php foreach($usersProducts as $usersProduct) : ?>
					<option value="<?= $usersProduct['product_id'] ?>">
					<?= $usersProduct['name'].' '.$usersProduct['description'].' '.$usersProduct['value'] ?><?= $user['user_id'] > 0 ? " Kč" : "" ?>
					</option>
				<?php endforeach ?>
			</select>	
			<input type="text" name="event" class="form-control" id="InputEvent"  placeholder="Popište pojistnou událost"></input>
			<button type="submit" class="btn btn-primary mt-3 mb-5 <?= $user['user_id'] > 0 ? "" : "d-none" ?>">Zadat</button>
		</form>	
	</div>
</div>
<div class="row justify-content-center <?= $user['user_id'] > 0 ? "" : "pt-5" ?>">
	<div class="col-lg-11 col-xl-8 pt-2"><h3>Události uživatele</h3></div>
	<div class="col-lg-11 col-xl-8 pt-2">
		<table class="table table-striped table-hover">
			<thead class="thead-light">
				<tr>
					<th>Název produktu</th>
					<th>Předmět</th>
					<th>Hodnota</th>
					<th>Autor události</th>
					<th>Událost</th>
					<th>Datum vzniku</th>
				</tr>
			</thead>	
			<tbody>
				<?php foreach($usersEvents as $usersEvent) : ?>
					<tr>
						<td><?= $usersEvent['name'] ?></td>
						<td><?= $usersEvent['subject'] ?></td>
						<td><?= $usersEvent['value'] ?><?= $user['user_id'] > 0 ? " Kč" : "" ?></td>
						<td><?= $usersEvent['author'] ?></td>
						<td><?= $usersEvent['event'] ?></td>
						<td><?= $usersEvent['created'] ?></td>						
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>