<div class="row p-3 justify-content-center">                      
<div class="col-4">
<form method="post">
  <div class="form-group">
    <label for="InputEmail">E-mail:</label>
    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" placeholder="váš e-mail">
    <small id="emailHelp" class="form-text text-muted">Zadejte přihlašovací e-mail</small>
  </div>
  <div class="form-group py-1">
    <label for="Password">Heslo:</label>
    <input type="password" name="password" class="form-control" id="InputPassword" aria-describedby="passwordHelp" placeholder="vaše heslo">
	<small id="passwordHelp" class="form-text text-muted">Zadejte vaše heslo do tohoto systému</small>
  </div>
  <button type="submit" class="btn btn-primary my-3">Přihlásit</button>
</form>

<div class="py-3">Pokud ještě nemáte účet, zaregistrujte se <a href="register">ZDE</a>.</div>		

</div>		
</div>