<div class="row p-3 justify-content-center">                      
<div class="col-4">
<form method="post" autocomplete="off">
  <div class="form-group py-1">
    <label for="InputFname">Jméno:</label>
    <input type="text" name="fname" class="form-control" id="InputFname" aria-describedby="fnameHelp" placeholder="křestní jméno">
    <small id="fnameHelp" class="form-text text-muted d-none">Zadejte křestní jméno</small>
  </div>
  <div class="form-group py-1">
    <label for="InputLname">Příjmení:</label>
    <input type="text" name="lname" class="form-control" id="InputLname" aria-describedby="lnameHelp" placeholder="příjmení">
    <small id="lnameHelp" class="form-text text-muted d-none">Zadejte příjmení</small>
  </div>
  <div class="form-group">
    <label for="InputEmail py-1">E-mail:</label>
    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" placeholder="e-mail">
    <small id="emailHelp" class="form-text text-muted d-none">Zadejte přihlašovací e-mail</small>
  </div>
  <div class="form-group py-1">
    <label for="Password">Heslo:</label>
    <input type="password" name="password" autocomplete="new-password" class="form-control" id="InputPassword" aria-describedby="passwordHelp" placeholder="heslo">
	<small id="passwordHelp" class="form-text text-muted">Zvolte heslo</small>
  </div>
  <div class="form-group py-1">
    <label for="Password">Heslo znovu:</label>
    <input type="password" name="passwordAgain" autocomplete="new-password" class="form-control" id="InputPasswordAgain" aria-describedby="passwordHelp" placeholder="znovu heslo">
	<small id="passwordHelpAgain" class="form-text text-muted">Pro kontrolu heslo ještě jednou</small>
  </div>
  <div class="form-group py-1">
    <label for="InputPhone">Telefonní číslo:</label>
    <input type="text" name="phone" class="form-control" id="InputPhone" aria-describedby="phoneHelp" placeholder="telefonní číslo">
    <small id="phoneHelp" class="form-text text-muted d-none">Zadejte telefonní číslo</small>
  </div>
  <div class="form-group py-1">
    <label for="InputStreet">Ulice:</label>
    <input type="text" name="street" class="form-control" id="InputStreet" aria-describedby="streetHelp" placeholder="Ulice">
    <small id="streetHelp" class="form-text text-muted d-none">Zadejte ulici a číslo popisné/orientační</small>
  </div>
  <div class="form-group py-1">
    <label for="InputStreet">Město:</label>
    <input type="text" name="city" class="form-control" id="InputCity" aria-describedby="cityHelp" placeholder="město">
    <small id="cityHelp" class="form-text text-muted d-none">Zadejte město</small>
  </div>
  <div class="form-group py-1">
    <label for="InputZIP">PSČ:</label>
    <input type="text" name="zip" class="form-control" id="InputZIP" aria-describedby="zipHelp" placeholder="PSČ">
    <small id="zipHelp" class="form-text text-muted d-none">Zadejte PSČ</small>
  </div>
  <button type="submit" class="btn btn-primary mt-3 mb-5">Uložit</button>
</form>	
</div>		
</div>