<div class="row p-3 justify-content-center">                      
<div class="col-6">
<form method="post" autocomplete="off" action="products/<?= isset($_SESSION['product']) ? 'edit' : 'new'?>">
  <div class="form-group d-none">
    <label for="InputID">ID:</label>
    <input type="text" name="id" class="form-control" id="InputID" value="<?= isset($_SESSION['product']) ? htmlspecialchars($_SESSION['product']['id']) : "" ?>">
  </div>
  <div class="form-group">
    <label for="InputName">Název:</label>
    <input type="text" name="name" class="form-control" id="InputName" aria-describedby="nameHelp" placeholder="název produktu" value="<?= isset($_SESSION['product']) ? htmlspecialchars($_SESSION['product']['name']) : "" ?>">
    <small id="nameHelp" class="form-text text-muted d-none">Zadejte název produktu</small>
  </div>
  <div class="form-group py-1">
    <label for="InputDescription">Popis:</label>
    <input type="text" name="description" class="form-control" id="InputDescription" aria-describedby="descriptionHelp" placeholder="popis produktu" value="<?= isset($_SESSION['product']) ? htmlspecialchars($_SESSION['product']['description']) : "" ?>">
    <small id="descriptionHelp" class="form-text text-muted d-none">Zadejte popis produktu</small>
  </div>
  <button type="submit" class="btn btn-primary mt-3 mb-5"><?= isset($_SESSION['product']) ? 'Upravit' : 'Založit' ?></button>
</form>
</div>		
</div>	
<div class="row justify-content-center">
	<div class="col-lg-11 col-xl-8 pt-2"><h3>Výpis produktů</h3></div>
	<div class="col-lg-11 col-xl-8 pt-2">
		<table class="table table-striped table-hover">
			<thead class="thead-light">
				<tr>
					<th>ID</th>
					<th>Název produktu</th>
					<th>Popis</th>
					<th>Stav</th>
					<th>Datum vzniku</th>
					<th>Akce</th>
				</tr>
			</thead>	
			<tbody>
				<?php foreach($products as $product) : ?>
					<tr>
						<td><?= $product['id'] ?></td>
						<td><?= $product['name'] ?></td>
						<td><?= $product['description'] ?></td>
						<td><?= $product['status'] ?></td>
						<td><?= $product['created'] ?></td>
						<td class="text-nowrap">
							<a class="btn btn-secondary" href="products/edit/<?= $product['id'] ?>">Upravit</a>
							<a class="btn btn-secondary" href="products/del/<?= $product['id'] ?>">Odstranit</a>
						</td>						
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>