<div class="row justify-content-center">
	<div class="col-lg-11 col-xl-8 pt-2"><h3 class="py-3">Výpis sjednaných produktů klienta <?= isset($user['info']['fname']) ? htmlspecialchars($user['info']['fname']) : "" ?> <?= isset($user['info']['lname']) ? htmlspecialchars($user['info']['lname']) : "" ?></h3></div>
</div>
<div class="row justify-content-center">	
	<div class="col-lg-11 col-xl-8 pt-2">
		<table class="table table-striped table-hover">
			<thead class="thead-light">
				<tr>
					<th class="d-none">ID</th>
					<th>Název produktu</th>
					<th>Předmět</th>
					<th>Hodnota</th>
					<th>Platnost do</th>
				</tr>
			</thead>	
			<tbody>
				<?php foreach($usersProducts as $usersProduct) : ?>
					<tr>
						<td class="d-none"><?= $usersProduct['product_id'] ?></td>
						<td><?= $usersProduct['name'] ?></td>
						<td><?= $usersProduct['subject'] ?></td>
						<td><?= $usersProduct['value'] ?></td>
						<td><?= $usersProduct['valid_to'] ?></td>						
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>
<div class="row justify-content-center">
	<div class="col-lg-11 col-xl-8 pt-2"><h3 class="py-3">Dostupné produkty:</h3></div>
</div>
<div class="row justify-content-center">	
	<div class="col-lg-11 col-xl-8 pt-2">
		<form method="post" action="products/add">
			<input type="text" name="user_id" class="form-control d-none" id="InputID" value="<?= isset($user['info']['id']) ? htmlspecialchars($user['info']['id']) : "" ?>"></input>
			<select  class="form-control my-1" id="ListRole" name="product_id">
				<?php foreach($products as $product) : ?>
					<option value="<?= $product['id'] ?>"><?= htmlspecialchars($product['name'].' '.$product['description']) ?></option>
				<?php endforeach ?>
			</select>
			<input type="text" name="subject" class="form-control my-1" id="InputSubject" placeholder="Zadejte předmět pojištění"></input>
			<input type="number" name="value" class="form-control my-1" id="InputValue" placeholder="Zadejte pojistnou částka"></input>
			<input type="date" name="valid_from" class="form-control d-none" id="InputValidFrom" value="<?= date('Y-m-d') ?>"></input>
			<input type="date" name="valid_to" class="form-control d-none" id="InputValidTo" value="<?= date('Y-m-d', strtotime('+1 year')) ?>"></input>
			<button type="submit" class="btn btn-primary mt-3 mb-5">Sjednat</button>
		</form>		
	</div>
</div>