<?php
	if($_SESSION['current_user']['role_id'] <= 3)
		require_once('Profile_Products.phtml');
?>
<div class="row justify-content-center">
<div class="col-4">
<form method="post" autocomplete="off" action="profile<?= isset($user['info']['id']) ? '/'.htmlspecialchars($user['info']['id']) : '' ?>">
  <div class="form-group d-none">
    <label for="InputID">ID:</label>
    <input type="text" name="id" class="form-control" id="InputID"value="<?= isset($user['info']['id']) ? htmlspecialchars($user['info']['id']) : "" ?>">
  </div>
  <div class="form-group py-1">
    <label for="InputFname">Jméno:</label>
    <input type="text" name="fname" class="form-control" id="InputFname" aria-describedby="fnameHelp" placeholder="Křestní jméno" value="<?= isset($user['info']['fname']) ? htmlspecialchars($user['info']['fname']) : "" ?>">
    <small id="fnameHelp" class="form-text text-muted d-none">Zadejte vaše křestní jméno</small>
  </div>
  <div class="form-group py-1">
    <label for="InputLname">Příjmení:</label>
    <input type="text" name="lname" class="form-control" id="InputLname" aria-describedby="lnameHelp" placeholder="Příjmení" value="<?= isset($user['info']['lname']) ? htmlspecialchars($user['info']['lname']) : "" ?>">
    <small id="lnameHelp" class="form-text text-muted d-none">Zadejte vaše příjmení</small>
  </div>
  <div class="form-group">
    <label for="InputEmail py-1">E-mail:</label>
    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" placeholder="váš e-mail" value="<?= isset($user['info']['email']) ? htmlspecialchars($user['info']['email']) : "" ?>">
    <small id="emailHelp" class="form-text text-muted d-none">Zadejte přihlašovací e-mail</small>
  </div>
  <div class="form-group py-1">
    <label for="Password">Heslo:</label>
    <input type="password" name="password" autocomplete="new-password" class="form-control" id="InputPassword" aria-describedby="passwordHelp" placeholder="vaše heslo">
	<small id="passwordHelp" class="form-text text-muted">Zvolte si heslo</small>
  </div>
  <div class="form-group py-1">
    <label for="Password">Heslo znovu:</label>
    <input type="password" name="passwordAgain" autocomplete="new-password" class="form-control" id="InputPasswordAgain" aria-describedby="passwordHelp" placeholder="znovu vaše heslo">
	<small id="passwordHelpAgain" class="form-text text-muted">Pro kontrolu heslo ještě jednou</small>
  </div>
  <div class="form-group py-1">
    <label for="InputPhone">Telefonní číslo:</label>
    <input type="text" name="phone" class="form-control" id="InputPhone" aria-describedby="phoneHelp" placeholder="Telefonní číslo" value="<?= isset($user['info']['phone']) ? htmlspecialchars($user['info']['phone']) : "" ?>">
    <small id="phoneHelp" class="form-text text-muted d-none">Zadejte vaše telefonní číslo</small>
  </div>
  <div class="form-group py-1">
    <label for="InputStreet">Ulice:</label>
    <input type="text" name="street" class="form-control" id="InputStreet" aria-describedby="streetHelp" placeholder="Ulice" value="<?= isset($user['address']['street']) ? htmlspecialchars($user['address']['street']) : "" ?>">
    <small id="streetHelp" class="form-text text-muted d-none">Zadejte vaši ulici a číslo popisné/orientační</small>
  </div>
  <div class="form-group py-1">
    <label for="InputStreet">Město:</label>
    <input type="text" name="city" class="form-control" id="InputCity" aria-describedby="cityHelp" placeholder="Město" value="<?= isset($user['address']['city']) ? htmlspecialchars($user['address']['city']) : "" ?>">
    <small id="cityHelp" class="form-text text-muted d-none">Zadejte město</small>
  </div>
  <div class="form-group py-1">
    <label for="InputZIP">PSČ:</label>
    <input type="text" name="zip" class="form-control" id="InputZIP" aria-describedby="zipHelp" placeholder="PSČ" value="<?= isset($user['address']['zip']) ? htmlspecialchars($user['address']['zip']) : "" ?>">
    <small id="zipHelp" class="form-text text-muted d-none">Zadejte PSČ</small>
  </div>
  <div class="form-group py-1">
    <label for="InputRole">Role:</label>
      <select  class="form-control" id="ListRole" name="role_id" <?= $authUserRole > 2 ? 'disabled="disabled" tabindex="-1"' : "" ?>>
          <?php foreach($roles as $role) : ?>
              <option value="<?= $role['id'] ?>" <?= $role['id'] == $user['info']['role_id'] ? "selected" : ""?>><?= htmlspecialchars($role['name']) ?></option>
          <?php endforeach ?>
      </select>
      <small id="roleHelp" class="form-text text-muted d-none">Zvolte roli</small>
  </div>
  <button type="submit" class="btn btn-primary mt-3 mb-5">Aktualizovat</button>
</form>	
</div>		
</div>