<div class="row p-3 justify-content-center">
<div class="col-4">
<form  name="RegisterForm" method="post" autocomplete="off" onsubmit="return validateRegisterForm()">
  <div class="form-group">
    <label for="InputEmail">E-mail:</label>
    <input type="email" name="email" class="form-control" id="InputEmail" aria-describedby="emailHelp" placeholder="váš e-mail">
    <small id="emailHelp" class="form-text text-muted">Zadejte e-mailovou adresu, kterou se budete přihlašovat</small>
  </div>
  <div class="form-group py-1">
    <label for="InputPassword">Heslo:</label>
    <input type="password" autocomplete="new-password" name="password" class="form-control" id="InputPassword" aria-describedby="passwordHelp" placeholder="vaše heslo">
	<small id="passwordHelp" class="form-text text-muted">Zvolte si heslo</small>
  </div>
  <div class="form-group py-1">
    <label for="InputPasswordAgain">Heslo znovu:</label>
    <input type="password" autocomplete="new-password" name="passwordAgain" class="form-control" id="InputPasswordAgain" aria-describedby="passwordHelp" placeholder="znovu vaše heslo">
	<small id="passwordHelpAgain" class="form-text text-muted">Pro kontrolu heslo ještě jednou</small>
  </div>
  <div class="form-group py-1">
  <?= $captcha['HtmlCode'] ?>
  </div>
  <button type="submit" class="btn btn-primary mt-3 mb-5">Registrovat</button>
</form>

<div class="py-3">Pokud jste tu omylem, návrat na úvodní stránku <a href="/">ZDE</a>.</div>	

</div>		
</div>