<div class="row justify-content-center pb-5">
	<div class="col-lg-11 col-xl-8 pt-2">
		<table class="table table-striped table-hover">
			<thead class="thead-light">
				<tr>
					<th>Jméno</th>
					<th>Přímení</th>
					<th>E-mail</th>
					<th>Tel. č.</th>
                    <th>Role</th>
                    <th>Status</th>
					<th>Detail</th>
				</tr>
			</thead>	
			<tbody>
				<?php foreach($clients as $client) : ?>
					<tr>
						<td><?= $client['fname'] ?></td>
						<td><?= $client['lname'] ?></td>
						<td><?= $client['email'] ?></td>
						<td><?= $client['phone'] ?></td>
                        <td>
							<form method="post"  class="form-inline input-group">
								<input type="text" name="id" class="form-control d-none" id="InputID"value="<?= isset($client['id']) ? htmlspecialchars($client['id']) : "" ?>">
								<select  class="form-control input-group-select" id="ListRole" name="role_id" <?= $client['role_id'] <= 2 ? $forAdminOnly : "" ?>>
								<?php foreach($roles as $role) : ?>
									<option value="<?= $role['id'] ?>" <?= $role['id'] == $client['role_id'] ? "selected" : ""?>><?= htmlspecialchars($role['name']) ?></option>
								<?php endforeach ?>
								</select>
								<button type="submit" class="btn btn-primary"><span class="material-symbols-outlined">check</span></button>
							</form>
						</td>
                        <td>
							<form method="post" class="form-inline input-group">
								<input type="text" name="id" class="form-control d-none" id="InputID"value="<?= isset($client['id']) ? htmlspecialchars($client['id']) : "" ?>">
								<select  class="form-control input-group-select" id="ListStatus" name="status" <?= $client['role_id'] <= 2 ? $forAdminOnly : "" ?>>
								<?php foreach($statuses as $status) : ?>
									<option value="<?= $status ?>" <?= $status == $client['status'] ? "selected" : ""?>><?= htmlspecialchars($status) ?></option>
								<?php endforeach ?>
								</select>
								<button type="submit" class="btn btn-primary"><span class="material-symbols-outlined">check</span></button>
							</form>
						</td>
						<td><a class="btn btn-secondary" href="profile/<?= $client['id'] ?>"><span class="material-symbols-outlined">more_horiz</span></a></td>						
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
</div>